language: python
python:
  - 3.4
  - 3.5
  - 3.6
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - python setup.py develop

script:
  - pytest tests
  - py.test --cov=myproj tests/
